name = "liventra-media"
compatibility_date = "2026-06-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[assets]
directory = "./out"

[vars]
YOUTUBE_CHANNEL_ID = "UCLeBqaOXvbonWYYhr9MdHTA"
